import { TYPE_SETPROFILE, VALUE_FALSE, VALUE_TRUE,
  TYPE_CLOSELOGIN, TYPE_OPENLOGIN, TYPE_OPENSIGNIN } from "./constants";
// ACTIONS
export const ACTION_HIDEPROFILE = { type: TYPE_SETPROFILE, value: VALUE_FALSE };
export const ACTION_SHOWPROFILE = { type: TYPE_SETPROFILE, value: VALUE_TRUE };
export const ACTION_CLOSELOGIN = { type: TYPE_CLOSELOGIN };
export const ACTION_OPENLOGIN = { type: TYPE_OPENLOGIN };
export const ACTION_OPENSIGNIN = { type: TYPE_OPENSIGNIN };
